### ISSUE TITLE
Error when starting up program: XML Issue

### ISSUE THREAD

**Issue by Phoxtane** [WindmillHelix/Brickficiency2#13]
When I started up Brickficiency 2 this morning, I got this error: https://dl.dropboxusercontent.com/u/84375076/Screenshot%202016-09-22%2017.25.13.png

`Error loading settings... using defaults (System.InvalidOperationException: There is an error in XML document (0, 0). ---> System.Xml.XmlException: Root element is missing.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   at System.Xml.XmlReader.MoveToContent()
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderSettings.Read3_Settings()
   --- End of inner exception stack trace ---
   at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, XmlDeserializationEvents events)
   at System.Xml.Serialization.XmlSerializer.Deserialize(Stream stream)
   at Brickficiency.MainWindow.loadWorker_DoWork(Object sender, DoWorkEventArgs e) in D:\github\Brickficiency2\Brickficiency\Main.cs:line 328)Loading...`

Currently, I can't use any of the options in the drop-down menus. This makes it a bit difficult to use the program.

The first thing I tried was re-extracting from the copy of the zip that I had on my PC (no dice). The second was to re-download the zip from Github and then try extracting from that (no dice either).

The problem only started today after a set of Windows updates (Windows 7 SP1).

Thanks!

**Comment by esampsonite** [comment]
Sounds like your settings file got corrupted somehow.  I'm going to be overhauling that section eventually to make it a bit more resilient, but to get back on your feet go into your %appdata%\Brickficiency folder (usually C:\Users<your username>\AppData\Roaming\Brickficiency) and delete the Brickficiency-Settings.xml file and then try to start the app.

**Comment by Phoxtane** [comment]
That's fixed it. Thanks!
