### ISSUE TITLE
Brickficiency won't start

### ISSUE THREAD

**Issue by 458Italia** [WindmillHelix/Brickficiency2#23]
The program won't start working. The folloeing message appears.

Error loading settings... using defaults (System.InvalidOperationException: There is an error in XML document (0, 0). ---> System.Xml.XmlException: Root element is missing.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   at System.Xml.XmlReader.MoveToContent()
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderSettings.Read3_Settings()
   --- End of inner exception stack trace ---
   at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, XmlDeserializationEvents events)
   at System.Xml.Serialization.XmlSerializer.Deserialize(Stream stream)
   at Brickficiency.MainWindow.loadWorker_DoWork(Object sender, DoWorkEventArgs e) in D:\github\Brickficiency2\Brickficiency\Main.cs:line 236)Loading...

**Comment by stoeffel85** [comment]
For me it worked nicely since a couple of days ago. Then it seems wanting to call my credentials for Bricklick and crashes.
